# Generated by Django 4.2.17 on 2024-12-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('caretakers', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
    ]
