# Generated by Django 4.2.17 on 2024-12-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('contacts', '0001_initial'),
        ('caretakers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='caretakers', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='pets',
            field=models.ManyToManyField(blank=True, related_name='caretakers', to='pets.pet'),
        ),
    ]
