# Generated by Django 4.2.17 on 2024-12-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('chip', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(upload_to='pets/images')),
                ('contacts', models.ManyToManyField(blank=True, to='contacts.contact')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
