# Generated by Django 4.2.17 on 2025-01-01 12:06

from django.db import migrations, models
import django.db.models.deletion
import entries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_alter_pet_contacts'),
        ('caretakers', '0003_alter_caretaker_contacts_alter_caretaker_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('recorded_on', models.DateTimeField(verbose_name='date recorded')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_event', models.BooleanField(default=False, verbose_name='is event?')),
                ('caretakers', models.ManyToManyField(related_name='entries', to='caretakers.caretaker')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(decimal_places=1, max_digits=4)),
                ('unit', models.CharField(choices=[('lbs', 'pounds'), ('°F', 'degrees Fahrenheit'), ('bpm', 'beats per minute'), ('breaths/min', 'breaths per minute')], max_length=11)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.entry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entries/images')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='entries.entry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.ForeignKey(default=entries.models.Category.get_default_id, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='kinds', to='entries.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='kind',
            field=models.ForeignKey(default=entries.models.Kind.get_default_id, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='entries', to='entries.kind'),
        ),
        migrations.AddField(
            model_name='entry',
            name='pets',
            field=models.ManyToManyField(related_name='entries', to='pets.pet'),
        ),
    ]
