# Generated by Django 4.2.17 on 2025-01-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
