# Generated by Django 4.2.17 on 2025-01-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='unit',
            field=models.CharField(choices=[('lbs', 'lbs'), ('°F', '°F'), ('bpm', 'bpm'), ('breaths/min', 'breaths/min')], max_length=11),
        ),
    ]
