# Generated by Django 4.2.17 on 2025-01-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='unit',
        ),
        migrations.AddField(
            model_name='entry',
            name='is_completed',
            field=models.BooleanField(default=True, verbose_name='completed?'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='entry_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entries.entry'),
            preserve_default=False,
        ),
    ]
