# Generated by Django 4.2.17 on 2025-03-24 16:00

from django.db import migrations, models
import django.db.models.deletion


def populate_polymorphic_ctype_id(apps, schema_editor):
    Entry = apps.get_model('entries', 'Entry')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    new_ct = ContentType.objects.get_for_model(Entry)
    Entry.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entries', '0006_remove_vitals_entry_remove_vitals_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-recorded_on']},
        ),
        migrations.AlterModelOptions(
            name='vitals',
            options={'ordering': ['-recorded_on']},
        ),
        migrations.AddField(
            model_name='entry',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(populate_polymorphic_ctype_id, migrations.RunPython.noop)
    ]
